#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/my_pay?useSSL=false&allowPublicKeyRetrieval=true
#    username: mysqluser
#    password: mysqlpw
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update